version: "3"

services:
  auth:
    build: ./authServer
    restart: unless-stopped
    ports:
      - 4000:4000
    env_file:
      - ./authServer/.env
    depends_on:
      - mongodb
    links:
      - "mongodb"
  todo:
    build: ./todoServer
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ./todoServer/.env
    depends_on:
      - mongodb
    links:
      - "mongodb"
      - "auth"
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   links:
  #     - auth
  #     - todo
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040
