version: "3"

services:
  auth:
    build: ./authServer
    ports:
      - 4000:4000
    env_file:
      - ./authServer/.env
    depends_on:
      - mongodb
    links:
      - "mongodb"
  todo:
    build: ./todoServer
    ports:
      - 8080:8080
    env_file:
      - ./todoServer/.env
    depends_on:
      - mongodb
    links:
      - "mongodb"
      - "auth"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    depends_on:
      - auth
      - todo
    links:
      - auth
      - todo
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
