
POST http://localhost:4000/createUser
Content-Type: application/json

{
  "name": "Andrew",
  "email": "andrewwang132@gmail.com",
  "username": "dies33",
  "password": "andrew1"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1"
}

###

DELETE http://localhost:4000/logout 
Content-Type: application/json 

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc0NDk1ODAsImRhdGEiOnsidXNlciI6ImRpZXMzNCIsImVtYWlsIjoiYW5kcmV3d2FuZzEzM0BnbWFpbC5jb20ifSwiaWF0IjoxNjk3NDQ1OTgwfQ.drJrSOqADnnxrs1R3N302fitmsU2HUnZRd8qthUdbzU"}



###
GET http://localhost:4000/verifyUser
Content-Type: application/json

{
  "username": "dies34",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ3MjM4NDEsImRhdGEiOiJkaWVzMzQiLCJpYXQiOjE2OTQ3MjAyNDF9.89MojotLE2dfm12mKQWQ327aXurBSXaQQBvuvacszno"
}

###
GET http://localhost:4000/validateUser
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1"
}

###

GET http://localhost:4000/verifyToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ3MjQ4MTMsImRhdGEiOnsidXNlciI6ImRpZXMzNCIsImVtYWlsIjoiYW5kcmV3d2FuZzEzM0BnbWFpbC5jb20ifSwiaWF0IjoxNjk0NzIxMjEzfQ.5-mDY0gOdZnPB-M8kYVaJJdVyCkdO6N0tZ28UCIasGs"}

###
GET http://localhost:4000/activeTokens

###
POST http://localhost:8080/todo
Content-Type: application/json 

{
  "username": "dies34",
  "todo": "be spiderman",
  "column": "Habits",
  "dueDate": "2025"
}
###
GET http://localhost:8080/todo
Content-Type: application/json 

{
  "username": "dies34",
  "column": "Habits"
}
###
PUT http://localhost:8080/column
Content-Type: application/json 

{
  "username": "dies35",
  "oldColumn": "Habit",
  "newColumn": "rab"
}
###
POST http://localhost:8080/column
Content-Type: application/json 

{
  "username": "dies35",
  "column": "Habits"
}

###
GET http://localhost:8080/column
Content-Type: application/json 

{
  "username": "dies35"
}
###
DELETE http://localhost:8080/column
Content-Type: application/json 

{
  "username": "dies35",
  "column": "Habits"
}
###

GET http://localhost:4000/findUser
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1"
}

###

POST http://localhost:8080/todo
Content-Type: application/json

{
  "username": "dies34",
  "column":"Habits",
  "todo": "Be Spiderman",
  "dueDate": "2025"
}

###

DELETE http://localhost:8080/todo
Content-Type: application/json

{
  "username": "dies35",
  "column": "gang",
  # "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todoId": 6
}

###

PUT http://localhost:8080/todo
Content-Type: application/json

{
  "username": "dies35",
  "column": "gang",
  # "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todoId": 4,
  "newTodo": "Be Wonderwoman"
}
###

PUT http://localhost:8080/todo/Column
Content-Type: application/json

{
  "username": "dies35",
  "column": "gang",
  # "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todoId": 5,
  "newColumn": "cc"
}
###

PUT http://localhost:8080/todo/Date
Content-Type: application/json

{
  "username": "dies35",
  "column": "gang",
  # "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todoId": 4,
  "newDate": "2035"
}

###

GET http://localhost:8080/findTodo
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1",
  "todo": "Save the World"
}

###

GET http://localhost:8080/getAllTodos
Content-Type: application/json

{
  "username": "dies34",
  "sessionId": "andrew1"
}