GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5MjUyMTI2OSwiZXhwIjoxNjkyNTIxMjg0fQ.1xmT-sagioXODnN6ByFzmyC4O7ZxvfcmsUbcxg646gk

###

DELETE http://localhost:4000/logout
Content-Type: application/json 
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5MjUyMTQwOX0._JcIamZ0E2rMwwKI9YliL6PjLYw0iCbs40Jyts2-epg"
}
###

POST http://localhost:4000/token 
Content-Type: application/json 

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5MjUyMTQwOX0._JcIamZ0E2rMwwKI9YliL6PjLYw0iCbs40Jyts2-epg"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Kyle"
}