
POST http://localhost:4000/createUser
Content-Type: application/json

{
  "name": "Andrew",
  "email": "andrewwang133@gmail.com",
  "username": "dies34",
  "password": "andrew1"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1"
}

###

DELETE http://localhost:4000/logout 
Content-Type: application/json 

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ3MjQ3NjAsImRhdGEiOnsidXNlciI6ImRpZXMzNCIsImVtYWlsIjoiYW5kcmV3d2FuZzEzM0BnbWFpbC5jb20ifSwiaWF0IjoxNjk0NzIxMTYwfQ.LH2Cd-n3mxH5ozAzyNrUDFaVA_7YUZjxc_hgVbehzHA"}



###
GET http://localhost:4000/verifyUser
Content-Type: application/json

{
  "username": "dies34",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ3MjM4NDEsImRhdGEiOiJkaWVzMzQiLCJpYXQiOjE2OTQ3MjAyNDF9.89MojotLE2dfm12mKQWQ327aXurBSXaQQBvuvacszno"
}

###
GET http://localhost:4000/validateUser
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1"
}

###

GET http://localhost:4000/verifyToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ3MjQ4MTMsImRhdGEiOnsidXNlciI6ImRpZXMzNCIsImVtYWlsIjoiYW5kcmV3d2FuZzEzM0BnbWFpbC5jb20ifSwiaWF0IjoxNjk0NzIxMjEzfQ.5-mDY0gOdZnPB-M8kYVaJJdVyCkdO6N0tZ28UCIasGs"}

###
GET http://localhost:4000/activeTokens

###
POST http://localhost:8080/createUserTodo
Content-Type: application/json 

{
  "username": "dies34",
  "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todo": "Get fucking rich",
  "dueDate": "2024"
}

###

GET http://localhost:4000/findUser
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1"
}

###

POST http://localhost:8080/storeTodo
Content-Type: application/json

{
  "username": "dies34",
  "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todo": "Be Superman",
  "dueDate": "2025"
}

###

DELETE http://localhost:8080/removeTodo
Content-Type: application/json

{
  "username": "dies34",
  "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todo": "Be batman"
}

###

PUT http://localhost:8080/updateTodo
Content-Type: application/json

{
  "username": "dies34",
  "sessionId": "eyJhbGciOiJIUzI1NiJ9.ZGllczM0.zAuNQDZeZC7SSi9jppgDlO8TSQcNrQKE4lYZJgTwJCM",
  "todo": "Be batman",
  "newTodo": "Be Wonderwoman"
}


###

GET http://localhost:8080/findTodo
Content-Type: application/json

{
  "username": "dies34",
  "password": "andrew1",
  "todo": "Save the World"
}

###

GET http://localhost:8080/getAllTodos
Content-Type: application/json

{
  "username": "dies34",
  "sessionId": "andrew1"
}